GG-5730 : Update to latest version of sbt-auto-build and drop Artifac…
hmrc/dynamic-stub pull request #20
Opened 2021-07-07 13:58 UTC by oarshad

…tory

2021-07-08 07:36 UTC, martin-armstrong requested changes

2021-07-08 07:36 UTC, martin-armstrong commented on project/plugins.sbt
> +addSbtPlugin("uk.gov.hmrc"        % "sbt-artifactory"     % "2.0.0")
SbtArtifactory can go as well

2021-07-08 07:36 UTC, martin-armstrong commented on build.sbt
> +  .enablePlugins(SbtArtifactory)
SbtArtifactory can go as well

2021-07-09 08:09 UTC, martin-armstrong approved these changes

2021-07-09 10:58 UTC, merged

2021-07-09 11:46 UTC, tim-holbrook reviewed
+1

2021-07-09 11:47 UTC, tim-holbrook reviewed
+1